import { readFile, writeFile, mkdir, cp } from 'node:fs/promises'
import { resolve } from 'node:path'
const destination = process.argv[2]
if (!destination) throw new Error('Usage: node scripts/export-local.mjs <dsh-ui-archived-local directory>')
const target = resolve(destination)
await mkdir(target, { recursive: true })
const client = (await readFile(new URL('../lib/client.cjs', import.meta.url), 'utf8')).replace(/^\/\/# sourceMappingURL=.*$/m, '')
await writeFile(resolve(target, 'client.js'), `// Generated by dsh-archived-panel/scripts/export-local.mjs. Do not edit.\nwindow.__ModuleLoader__.load({id: "dsh-ui-archived-local", factory: function(require) {\nvar module = {exports: {}}; var exports = module.exports;\n${client}\nreturn module.exports;\n}});\n`)
await cp(new URL('../src', import.meta.url), resolve(target, 'src'), { recursive: true })
await cp(new URL('../patches', import.meta.url), resolve(target, 'patches'), { recursive: true })
await cp(new URL('../CHANGELOG.md', import.meta.url), resolve(target, 'CHANGELOG.md'))
